- hosts: localhost
  become: true

  tasks:
    - name: Install packages
      apt:
        name:
          - build-essential
          - cmake
          - curl
          - fd-find
          - git
          - htop
          - ibus-mozc
          - ripgrep
          - tmux
          - vim
          - xclip
          - zsh
        state: present
        update_cache: true
