- hosts: localhost
  become: true

  tasks:
    - name: Install packages
      apt:
        name:
          - build-essential
          - cmake
          - curl 
          - git
          - htop
          - tmux
          - vim 
          - zsh 
        state: present
        update_cache: true
