- hosts: localhost
  gather_facts: false

  tasks:
    - name: Persist system keyboard layout and options
      become: true
      ansible.builtin.copy:
        dest: /etc/default/keyboard
        mode: '0644'
        content: |
          XKBMODEL="pc105"
          XKBLAYOUT="jp"
          XKBVARIANT=""
          XKBOPTIONS="ctrl:swapcaps"
          BACKSPACE="guess"
